---
title: "Voz Ativa: Respostas até agora"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(viridis)
source(here::here("code/lib.R"))
theme_set(theme_report())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      warning = F,
                      echo = FALSE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r read, warning=FALSE}
dados = read_projectdata()
```

*Atualizado em `r lubridate::now()`*

## Alguns números

```{r}
dados %>% 
    summarise(
        `Total de candidaturas` = n(),
        `Conseguimos email` = sprintf("%d (%.1f%%)", sum(recebeu), 100* sum(recebeu) / n()),
        `Responderam` = sprintf("%d (%.1f%%)", sum(respondeu), 100*sum(respondeu) / sum(recebeu)), 
    ) %>% 
    gather(key = "Número", value = "Valor") %>% 
    knitr::kable()

```

## Nosso progresso

```{r}
dados %>% 
    count(respondeu) %>% 
    mutate(Respondeu = if_else(respondeu, "Sim", "Não")) %>% 
    mutate(`Respondeu (%)` = n / sum(n) * 100) %>% 
    ggplot(aes(x = Respondeu, y = `Respondeu (%)`, fill = Respondeu)) + 
    geom_col(width = .2) + 
    theme(legend.position = "None") + 
    labs(title = "No geral")
```



```{r}
dados %>% 
    filter(!is.na(date_created)) %>% 
    select(date_created) %>% 
    arrange(date_created) %>% 
    mutate(i = 1, 
           Total = cumsum(i)) %>% 
    ggplot(aes(x = date_created, y = Total)) + 
    geom_line(color = "deeppink", size = 1.2) + 
    labs(title = "Número de respostas ao longo do tempo", 
         x = "Data", 
         y = "Respostas recebidas")
```


### Por UF

```{r}
dados %>% 
    count(uf, respondeu) %>% 
    mutate(Respondeu = if_else(respondeu, "Sim", "Não")) %>% 
    group_by(uf) %>% 
    mutate(`Respondeu (%)` = n / sum(n) * 100, 
           sucesso = min(`Respondeu (%)`)) %>% 
    ggplot(aes(x = reorder(uf, sucesso), y = `Respondeu (%)`, fill = Respondeu)) + 
    geom_col(position = "stack") + 
    coord_flip() + 
    labs(
        x = "",
        title = "Respostas por UF (em %)"
    )

```

```{r}
options(scipen = 999)
dados %>% 
    count(uf, respondeu) %>% 
    mutate(Respondeu = if_else(respondeu, "Sim", "Não")) %>% 
    ggplot(aes(x = reorder(uf, n), y = n, fill = Respondeu)) + 
    geom_col(position = "stack") + 
    coord_flip() + 
    labs(
        x = "",
        title = "Respostas por UF (em absoluto)",
        y = "Quantidade de candidaturas"
    )
```

### Por partido

```{r}
dados %>% 
    count(sg_partido, respondeu) %>% 
    mutate(Respondeu = if_else(respondeu, "Sim", "Não")) %>% 
    group_by(sg_partido) %>% 
    mutate(`Respondeu (%)` = n / sum(n) * 100, 
           sucesso = min(`Respondeu (%)`)) %>% 
    ggplot(aes(x = reorder(sg_partido, sucesso), 
               y = `Respondeu (%)`, 
               fill = Respondeu)) + 
    geom_col(position = "stack") + 
    coord_flip() + 
    labs(
        x = "",
        title = "Respostas por PARTIDO (em %)"
    )

```

```{r}
dados %>% 
    count(sg_partido, respondeu) %>% 
    mutate(Respondeu = if_else(respondeu, "Sim", "Não")) %>% 
    ggplot(aes(x = reorder(sg_partido, n), y = n, fill = Respondeu)) + 
    geom_col(position = "stack") + 
    coord_flip() + 
    labs(
        x = "",
        title = "Respostas por PARTIDO (em absoluto)",
        y = "Quantidade de candidaturas"
    )

```

```{r fig.width=8}
dados %>% 
    filter(recebeu) %>%
    count(sg_partido, uf, respondeu) %>% 
    # complete(sg_partido, uf, respondeu, fill = list(n = 0)) %>% 
    group_by(sg_partido, uf) %>% 
    mutate(prop = n / sum(n), total_no_estado = sum(n)) %>%
    filter(respondeu) %>% 
    ggplot(aes(x = reorder(sg_partido, prop), y =reorder(uf, prop, median), color = prop*100, size = total_no_estado)) + 
    geom_point(alpha = .8) + 
    scale_color_viridis(option = "B", direction = -1) + 
    coord_flip() + 
    labs(x = "", y = "", color = "% responderam", size = "Candidatos")
```

<!-- ### Por partido e UF -->

```{r fig.height=9, fig.width=9}

# dados %>% 
#     count(sg_partido, uf, respondeu) %>% 
#     mutate(Respondeu = if_else(respondeu, "Sim", "Não")) %>% 
#     group_by(sg_partido) %>% 
#     mutate(
#         respondeu_partido = n / sum(n),
#         sucesso = min(respondeu_partido)) %>% 
#     group_by(sg_partido, uf) %>% 
#     mutate(`Respondeu (%)` = n / sum(n) * 100) %>% 
#     ggplot(aes(x = reorder(sg_partido, sucesso), 
#                y = `Respondeu (%)`, 
#                fill = Respondeu)) + 
#     geom_col(position = "stack") + 
#     coord_flip() + 
#     facet_grid(. ~uf) + 
#     labs(
#         x = "",
#         title = "Respostas por PARTIDO (em %)"
#     )
```

